### ISSUE TITLE
Demographic questions, familiarity with the languages

### ISSUE THREAD

**Issue by saramontazeri** [melsod/OCSWinter2020#19]
1. The names of the 5 languages have been repeated in the question as well as in the options. Maybe it is not necessary to list them in the question as well.

2. I was wondering if it is a good idea to have two sections for this question:

Do you know any of the following languages? (If you choose Yes, then indicate which language/languages you are familiar with) 
Yes            No

Spanish    Tsimane    Yeli-Dnye     Tseltal      Mayan    Quechua  

3. The answer to this question should be multi-selected since the participants may know more than one of these languages (though unlikely)

**Comment by SmithBradleyC** [comment]
I think I want to leave it as 1 question but I've fixed this survey question (will push to Github later today) so that it makes more sense.
