### ISSUE TITLE
Inactive the answer choices until one listens to all the clips

### ISSUE THREAD

**Issue by saramontazeri** [melsod/OCSWinter2020#23]
In this experiment, I listened to just one of the clips among 10 clips, and then I could answer (without listening to the rest of the clips. I think it should be changed to this form that after the participant listens to ALL the clips, then the answer choices become active.
Because in the instruction part, listening to all the clips is mandatory and it says "You must listen to all audio clips before responding and if there are multiple audio clips they are guaranteed to be from the same child".

**Comment by SmithBradleyC** [comment]
This is a parameter in the code. I've set it so you only have to listen to 1 clip just so it's easier to debug. I'll change that parameter to 10 so that they have to listen to all 10 clips soon
