### ISSUE TITLE
Consent form wording change

### ISSUE THREAD

**Issue by melsod** [melsod/OCSWinter2020#27]
We say "We will put a link to any such further publications on the lab website." I think that's confusing and should probably be changed to "on the Open Science Framework page" or something like that.

That was probably my wording bad...

**Comment by melsod** [comment]
Also we say "SONA participants: you will be provided with a hard copy of the consent form to take home with you. " but then later "A printed copy of this form will be provided upon request. " I think the former is better.

**Comment by SmithBradleyC** [comment]
1. Wording is changed exactly as you suggest
2. Are you suggesting removing the second phrase entirely or changing it to be more similar to the first reference? I added in the second phrase "after" the consent form just to remind the participants to ask for a form if they wanted it.

**Comment by melsod** [comment]
I think given the wording that was passed through ethics, we should offer a copy of the consent form to all participants, so change it to be more similar to the first wording.

**Comment by SmithBradleyC** [comment]
Ok, I've changed it to say:

<p>SONA participants: you will be provided with a hard copy of the consent form presented above.</p>
<p>MTurk participants: please print this page if you want to keep a hard copy for your records.</p>
