### ISSUE TITLE
childcare experience suggestion

### ISSUE THREAD

**Issue by melsod** [melsod/OCSWinter2020#29]
Just a last-minute thought: I have extensive experience with infants (obviously) but answered 0 to both questions. I am wondering about a slight last-minute altering of the wording:

1. say something like "child care or related area" (to include other people like me who have significant exposure to infants but not as a child care worker).
2. make it clear that both paid and volunteer experience counts (assuming you want that)

**Comment by SmithBradleyC** [comment]
Changed to say "In the last 5 years, estimate how many months you have worked/volunteered in childcare or an area with significant exposure to infants? (answer '0' if none)"

Do we like that better?
